import type { Metadata } from "next";
import { IoMdMenu } from "react-icons/io";
import {
  Sheet,
  SheetContent,
  SheetDescription,
  SheetHeader,
  SheetTitle,
  SheetTrigger,
} from "@/components/ui/sheet"
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import { Footer } from "./components/Footer";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Muhammad Yafeh",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="hidden lg:block">
          <Navbar/>
          </div>
        <div className="lg:hidden m-3 ">
      <Sheet>
  <SheetTrigger><IoMdMenu /></SheetTrigger>
  <SheetContent>
    <SheetHeader>
      <SheetTitle>Muhammad Yafeh Portfolio</SheetTitle>
      <SheetDescription>
       
         <Navbar/>
      
      </SheetDescription>
    </SheetHeader>
  </SheetContent>
</Sheet>
        </div>
      {children}
      <Footer/>
      </body>
      
    </html>
  );
}
